name: antpowerbulb
dependencies:
- openssl=1.0.2d=0
- pip=7.1.2=py27_0
- python=2.7.10=2
- readline=6.2=2
- setuptools=18.4=py27_0
- sqlite=3.8.4.1=1
- wheel=0.26.0=py27_1
- zlib=1.2.8=0
- pip:
  - bitstring==3.1.5
  - colour==0.1.4
  - funcsigs==1.0.2
  - jsonpickle==0.9.4
  - lifxlan==1.0.4
  - mock==2.0.0
  - msgpack-python==0.4.8
  - numpy==1.13.0
  - pbr==3.1.1
  - pyserial==3.3
  - pyusb==1.0.0
  - rx==1.5.9
  - six==1.10.0